FROM registry.access.redhat.com/ubi9/ubi:latest@sha256:c5cc9c221baa8eb13093f90c31bb58c04d83f6afd14510d3496691f92566f99e as builder

USER root

# Konflux injects the prefetched RPM repositories into /etc/yum.repos.d.
# Restrict dnf to the local repositories even when testing outside Konflux.
RUN dnf --setopt=reposdir=/cachi2/output/deps/rpm/$(uname -m)/repos.d install -y \
    which patch gcc gcc-c++ clang cmake make openssl-devel libcurl-devel \
    ca-certificates unzip git findutils python3 python3-devel tar gzip && \
    dnf clean all

COPY prefetch-input/prepare-bazel-cache.sh /usr/local/bin/prepare-bazel-cache
RUN bash /usr/local/bin/prepare-bazel-cache

COPY . /mlmd-src
WORKDIR /mlmd-src

ENV BAZEL_JOBS=8

# "-std=c++17" is needed in order to build with ZetaSQL.
RUN bazel build -c opt --action_env=PATH \
  --repository_cache=/opt/bazel-repository-cache \
  --experimental_repository_disable_download \
  --define=grpc_no_ares=true \
  --copt="-Wno-maybe-uninitialized" \
  --jobs=${BAZEL_JOBS} \
  //ml_metadata/metadata_store:metadata_store_server \
  --cxxopt="-std=c++17" --host_cxxopt="-std=c++17" \
  --verbose_failures

# copying libmysqlclient source onto THIRD_PARTY folder.
RUN mkdir -p /mlmd-src/third_party
RUN cp -RL /mlmd-src/bazel-mlmd-src/external/libmysqlclient /mlmd-src/third_party/mariadb-connector-c

FROM registry.redhat.io/ubi9/ubi-minimal-pqc@sha256:a3f7ca6346ee5ca1867d1dcc79b011c5c711bf7a3e43c7cece3323d6d1ef5ac0

COPY --from=builder /mlmd-src/bazel-bin/ml_metadata/metadata_store/metadata_store_server /bin/metadata_store_server
COPY --from=builder /mlmd-src/third_party /mlmd-src/third_party

ENV GRPC_PORT "8080"
ENV METADATA_STORE_SERVER_CONFIG_FILE ""

# Introduces tzdata package here to avoid LoadTimeZone check failed error in the metadata store server.
# https://access.redhat.com/solutions/5616681
RUN microdnf --setopt=reposdir=/cachi2/output/deps/rpm/$(uname -m)/repos.d reinstall tzdata -y && \
    microdnf clean all

USER 65534:65534

ENTRYPOINT \
  "/bin/metadata_store_server" \
  "--grpc_port=${GRPC_PORT}" \
  "--metadata_store_server_config_file=${METADATA_STORE_SERVER_CONFIG_FILE}"

LABEL com.redhat.component="odh-mlmd-grpc-server" \
    name="odh-mlmd-grpc-server-rhel9" \
    description="odh-mlmd-grpc-server" \
    summary="odh-mlmd-grpc-server" \
    io.openshift.expose-services="8080" \
    io.openshift.tags="odh-mlmd-grpc-server" \
    io.k8s.display-name="odh-mlmd-grpc-server" \
    io.k8s.description="odh-mlmd-grpc-server"
