FROM registry.access.redhat.com/ubi9/ubi:latest AS builder

USER root

RUN curl -o /etc/yum.repos.d/copr-galileo-bazel.repo \
    https://copr.fedorainfracloud.org/coprs/galileo/bazel/repo/epel-9/galileo-bazel-epel-9.repo && \
    dnf install -y \
    which \
    patch \
    gcc \
    clang \
    cmake \
    make \
    openssl-devel \
    libcurl-devel \
    ca-certificates \
    unzip \
    git \
    findutils \
    python3 \
    bazel5 \
    && ARCH=$(uname -m) \
    && case "$ARCH" in \
         x86_64) \
           BAZEL_BIN=bazel-6.3.2-linux-x86_64; \
           BAZEL_URL=https://github.com/bazelbuild/bazel/releases/download/6.3.2/bazel-6.3.2-linux-x86_64 ;; \
         aarch64) \
           BAZEL_BIN=bazel-6.3.2-linux-aarch64; \
           BAZEL_URL=https://github.com/bazelbuild/bazel/releases/download/6.3.2/bazel-6.3.2-linux-arm64 ;; \
         ppc64le) \
           BAZEL_BIN=bazel-6.3.2-linux-ppc64le; \
           BAZEL_URL=https://ftp2.osuosl.org/pub/ppc64el/bazel/el8/bazel-6.3.2 ;; \
         *) echo "unsupported architecture: $ARCH" >&2; exit 1 ;; \
       esac \
    && curl -fLo "/usr/bin/${BAZEL_BIN}" "${BAZEL_URL}" \
    && chmod +x "/usr/bin/${BAZEL_BIN}"

COPY . /mlmd-src
WORKDIR /mlmd-src

# Running in offline mode with --nofetch arg, cache and deps must be cloned
# into the local root bazel cache
# "-std=c++17" is needed in order to build with ZetaSQL.
RUN ARCH=$(uname -m) && \
  EXTRA_COPTS="" && \
  if [ "$ARCH" = "ppc64le" ] || [ "$ARCH" = "aarch64" ]; then \
    EXTRA_COPTS='--copt=-D_FORTIFY_SOURCE=0 --host_copt=-D_FORTIFY_SOURCE=0 --copt=-Wno-error=stringop-overflow --host_copt=-Wno-error=stringop-overflow --copt=-Wno-error=stringop-overread --host_copt=-Wno-error=stringop-overread --copt=-Wno-error=array-bounds --host_copt=-Wno-error=array-bounds'; \
  fi && \
  bazel build -c opt --action_env=PATH \
  --define=grpc_no_ares=true \
  --copt="-Wno-maybe-uninitialized" \
  ${EXTRA_COPTS} \
  --jobs=4 \
  //ml_metadata/metadata_store:metadata_store_server \
  --cxxopt="-std=c++17" --host_cxxopt="-std=c++17"

# copying libmysqlclient source onto THIRD_PARTY folder.
RUN mkdir -p /mlmd-src/third_party
RUN cp -RL /mlmd-src/bazel-mlmd-src/external/libmysqlclient /mlmd-src/third_party/mariadb-connector-c

FROM registry.access.redhat.com/ubi9/ubi-minimal:latest

COPY --from=builder /mlmd-src/bazel-bin/ml_metadata/metadata_store/metadata_store_server /bin/metadata_store_server
COPY --from=builder /mlmd-src/third_party /mlmd-src/third_party

ENV GRPC_PORT "8080"
ENV METADATA_STORE_SERVER_CONFIG_FILE ""

# Introduces tzdata package here to avoid LoadTimeZone check failed error in the metadata store server.
RUN microdnf reinstall -y tzdata && \
    microdnf clean all

USER 65534:65534

ENTRYPOINT \
  "/bin/metadata_store_server" \
  "--grpc_port=${GRPC_PORT}" \
  "--metadata_store_server_config_file=${METADATA_STORE_SERVER_CONFIG_FILE}"
