apiVersion: tekton.dev/v1
kind: PipelineRun
#test4
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/opendatahub-io/ml-metadata?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    pipelinesascode.tekton.dev/cancel-in-progress: "false"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "pull_request" && target_branch
      == "master"
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: opendatahub-builds
    appstudio.openshift.io/component: odh-mlmd-grpc-server-ci
    pipelines.appstudio.openshift.io/type: build
  name: odh-mlmd-grpc-server-on-pull-request
  namespace: open-data-hub-tenant
spec:
  timeouts:
    pipeline: 8h
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/opendatahub/mlmd-grpc-server:odh-pr
  - name: dockerfile
    value: ml_metadata/tools/docker_server/Dockerfile.redhat
  - name: path-context
    value: .
  - name: additional-tags
    value:
    - 'odh-pr-{{revision}}'
  - name: pipeline-type
    value: pull-request
  taskRunSpecs:
    - pipelineTaskName: build-images
      stepSpecs:
        - name: build
          computeResources:
            requests:
              cpu: '8'
              memory: 16Gi
            limits:
              cpu: '16'
              memory: 32Gi
  pipelineRef:
    resolver: git
    params:
    - name: url
      value: https://github.com/opendatahub-io/odh-konflux-central.git
    - name: revision
      value: main
    - name: pathInRepo
      value: pipeline/multi-arch-container-build.yaml
  taskRunTemplate:
    serviceAccountName: build-pipeline-odh-mlmd-grpc-server
  workspaces:
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}